---@type LazySpec
return {
  { import = "plugins.languages.ansible" },
  { import = "plugins.languages.astro" },
  { import = "plugins.languages.c" },
  { import = "plugins.languages.containers" },
  { import = "plugins.languages.gleam" },
  { import = "plugins.languages.go" },
  { import = "plugins.languages.java" },
  { import = "plugins.languages.julia" },
  { import = "plugins.languages.just" },
  { import = "plugins.languages.k8s" },
  { import = "plugins.languages.lua" },
  { import = "plugins.languages.markdown" },
  { import = "plugins.languages.prisma" },
  { import = "plugins.languages.proto" },
  { import = "plugins.languages.python" },
  { import = "plugins.languages.ruby" },
  { import = "plugins.languages.rust" },
  { import = "plugins.languages.shell" },
  { import = "plugins.languages.sql" },
  { import = "plugins.languages.svelte" },
  { import = "plugins.languages.tailwindcss" },
  { import = "plugins.languages.terraform" },
  { import = "plugins.languages.toml" },
  { import = "plugins.languages.typescript" },
  { import = "plugins.languages.typst" },
  { import = "plugins.languages.vue" },
  { import = "plugins.languages.web" },
  { import = "plugins.languages.wgsl" },
  { import = "plugins.languages.xml" },
  { import = "plugins.languages.yaml" },
  { import = "plugins.languages.zig" },
}
